### ISSUE TITLE
Troubleshooting: Arguments increased on `ExportedFunction`

### ISSUE THREAD

**Issue by hskang9** [wasmerio/python-ext-wasm#73] opened 2019-09-01 02:41 UTC
### Summary

I have compiled a library to wrap in python using webassembly but the wrapped function requires a different number of arguments from the original rust code.

### Additional details

To reproduce the issue:

## install wasmer from pip

```bash
pip install wasmer
```

## Clone the repo and build wrapper lib into the target `wasm32-unknown-unknown`

```bash
git clone https://github.com/hskang9/schnorrkel-py.git
cd schnorrkel-py
cargo build --target wasm32-unknown-unknown
```

## Run python-ext-wasm
```python
from wasmer import Instance
from wasmer import Uint8Array
wasm_bytes = open('target/wasm32-unknown-unknown/release/schnorrkel_py.wasm', 'rb').read()
instance = Instance(wasm_bytes)

result = instance.exports.secret_from_seed([1, 2])

print(result)
```

The error shows that the exported function requires 3 arguments when the original rust code required one pointer to UInt8Array. 

here is the error log:
```bash
Traceback (most recent call last):
RuntimeError: Missing 2 argument(s) when calling `secret_from_seed`: Expect 3 argument(s), given 1.
```

Here is the rust code compiled to wasm:
```rust
#[no_mangle]
pub extern fn secret_from_seed(seed: &[u8]) -> Vec<u8> {
	__secret_from_seed(seed).to_vec()
}

pub fn __secret_from_seed(seed: &[u8]) -> [u8; SECRET_KEY_LENGTH] {
	let secret = keypair_from_seed(seed).secret.to_bytes();
	let mut s = [0u8; SECRET_KEY_LENGTH];
	s.copy_from_slice(&secret);
	s
}
```

My question is: 

1. How did the argument increase?
2. Did I compile the rust code to the right target?

**Comment by Mec-iS** [comment] 2019-09-01 10:25
you may find some hints on how to pass sequences in my article: https://dev.to/tuned/memory-views-handling-strings-48h7

> Did I compile the rust code to the right target?

yes, also double-check that your crate is defined as dynlib in the .toml file.

The problem is in the return type. You cannot return a Vec<u8> as there is no such type in WebAssembly. What you can return is a pointer to the cell at which the array starts, and by knowing the lenght you can read all its elements in the WebAssembly memory view. See [this example](https://github.com/Mec-iS/rust-wasm-python-101/blob/50ae7799bb0eeb725a5792dd1e83d258b70e21ae/src/strings.rs#L13)

**Comment by hskang9** [comment] 2019-09-01 23:31
Thank you @Mec-iS. will adding &Vec<u8> <-> &str converter to the rust wrapper code and making argument and return value types to hexstrings enable me to use the exported function with one string argument?

**Comment by hskang9** [comment] 2019-09-05 01:23
```
class Instance(object):
    """
    `Instance` is a Python class that represents a WebAssembly instance.
    
    # Examples
    
    ```python
    from wasmer import Instance
    
    instance = Instance(wasm_bytes)
    ```
    """
    def __init__(self, wasm_bytes): # real signature unknown; restored from __doc__
        pass

    @staticmethod # known case of __new__
    def __new__(*args, **kwargs): # real signature unknown
        """ Create and return a new object.  See help(type) for accurate signature. """
        pass

    exports = property(lambda self: object(), lambda self, v: None, lambda self: None)  # default
    """The `exports` getter."""

    memory = property(lambda self: object(), lambda self, v: None, lambda self: None)  # default
    """The `memory` getter."""
```

When I looked at the `wasmer.py` file, it just uses the built-in class initialization and put wasm_bytes as an argument. Does python language support wasm from its compiler?

**Comment by Hywan** [comment] 2019-09-06 09:30
> Does python language support wasm from its compiler?

Are you asking if a Python program can be compiled to WebAssembly? Or are you asking if a Python runtime already exists as a WebAssembly module?

**Comment by Mec-iS** [comment] 2019-11-23 13:24
> Thank you @Mec-iS. will adding &Vec <-> &str converter to the rust wrapper code and making argument and return value types to hexstrings enable me to use the exported function with one string argument?

It sounds easier to create a Python function in your glue code that accept two arguments: a list/bytestring and an instance; and return the position of the starting cell and the length of the array in the instance's memory view. Once you have these two bits of information you can pass both as `const* u8` to the Wasm function.

**Comment by Hywan** [comment] 2020-04-27 08:24
Is it solved? Closing for the moment. Feel free to reopen.

**Closed by Hywan** 2020-04-27 08:24 UTC
Labels: ❓ question
